name: better_router
description: the better router is a powerful, but for humans, flutter router.
version: 2.1.0
repository: https://github.com/dukex/better_router
environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=3.0.3"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
