name: better_router
description: the better router is a powerful, but for humans, flutter router.
version: 2.1.0
repository: https://github.com/dukex/better_router
environment:
  sdk: '>=2.17.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter
